FAT-42626: create one activity  3 fragments
chikebaba/android-task pull request #1
Opened 2022-09-25 15:42 UTC by chikebaba

first is 2 textview
second is echo plainText
third is recycler view with items
and drawerlayout with menu

2022-09-26 10:51 UTC, daddymercury commented
Hey @chikebaba , nice work by the way, please fix my comments

2022-09-26 11:07 UTC, daddymercury requested changes

2022-09-26 11:07 UTC, daddymercury commented on .idea/gradle.xml
>  <?xml version="1.0" encoding="UTF-8"?>
This type of file should not be included into GIT changes, please delete this file from Merge request Also please add into git ignore whole .idea directory

2022-09-26 11:07 UTC, daddymercury commented on .idea/misc.xml
>  <project version="4">
This type of file should not be included into GIT changes, please delete this file from Merge request Also please add into git ignore whole .idea directory

2022-09-26 11:07 UTC, daddymercury commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This type of file should not be included into GIT changes, please delete this file from Merge request Also please add into git ignore whole .idea directory

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/AndroidManifest.xml
> +        tools:targetApi="31">
In your Gradle file you have **targetSdk 33** please use the same here

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/CustomAdapter.kt
> +
```suggestion
```

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/CustomAdapter.kt
> +
Delete unnecessary  indents in the code

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/CustomAdapter.kt
> +        } // click event
```suggestion
        holder.itemTextView.setOnClickListener {  
            val builder = AlertDialog.Builder(it.context)
            with(builder)
            {
                setTitle("Picked item")
                setMessage("Item " + itemsList[position] )
                show()
            }
        }
```

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/CustomAdapter.kt
> +        } // click event
delete unnesesary commented code also please pay attention to white space and indents in the code

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/CustomAdapter.kt
> +
delete these 2 lines

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/CustomAdapter.kt
> +
delete this line

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/MainActivity.kt
> +        }*/
```suggestion 
```

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/MainActivity.kt
> +
Delete EMPTY lines

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/ui/gallery/GalleryFragment.kt
> +        // Toast.makeText(activity, "fragments onStart method", Toast.LENGTH_LONG).show()
Delete all commented code!

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/ui/gallery/GalleryFragment.kt
> +        watchedText.addTextChangedListener(object : TextWatcher {
user instead Kotlin do **_onTextChanged_** and delete Textwatcher if you don't use these 3 methods in 1 time

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/ui/gallery/GalleryFragment.kt
> +                // tvSample.setText("Text in EditText : "+s)
commented code should be deleted!

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/ui/gallery/GalleryFragment.kt
> +
empty lines

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/ui/slideshow/SlideshowFragment.kt
> +
empty lines

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/ui/slideshow/SlideshowFragment.kt
> +    //
delete it **//**

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/ui/slideshow/SlideshowFragment.kt
> +    //
delete it **//**

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/ui/slideshow/SlideshowFragment.kt
> +    //
delete it **//**

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/ui/slideshow/SlideshowFragment.kt
> +    //
delete it **//**

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/ui/slideshow/SlideshowFragment.kt
> +    slideshowViewModel.text.observe(viewLifecycleOwner) {
delete commented code

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/ui/slideshow/SlideshowFragment.kt
> +    }
Are you sure you need onDestroyView be commented?

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/java/com/example/android_task/ui/slideshow/SlideshowFragment.kt
> +
empty lines

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout-land/fragment_slideshow.xml
> +        android:layout_width="match_parent"
instead match_parent please use 0 dp

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout-land/fragment_slideshow.xml
> +        app:layout_constraintHorizontal_bias="1.0"
delete using bias

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout-land/fragment_slideshow.xml
> +        app:layout_constraintVertical_bias="0.011" />
delete using bias

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout-land/fragment_slideshow.xml
> +        android:layout_width="594dp"
no hardcoded allowed use constraint instead!

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout-land/fragment_slideshow.xml
> +        android:layout_height="227dp"
no hard code

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout-land/fragment_slideshow.xml
> +        app:layout_constraintHorizontal_bias="0.494"
delete using bias

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout-land/fragment_slideshow.xml
> +        app:layout_constraintVertical_bias="0.586" />
delete using bias

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout-land/fragment_slideshow.xml
> +
delete empty line

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout/app_bar_main.xml
> +    <!--<com.google.android.material.floatingactionbutton.FloatingActionButton
delte commented code

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout/fragment_gallery.xml
> +        android:layout_width="392dp"
no hard code

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout/fragment_gallery.xml
> +        android:layout_marginStart="8dp"
add this into [dimens](https://stackoverflow.com/questions/29128178/how-to-use-dimens-xml-in-android)

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout/fragment_gallery.xml
> +        android:layout_marginEnd="8dp"
add this into [dimens](https://stackoverflow.com/questions/29128178/how-to-use-dimens-xml-in-android)

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout/fragment_gallery.xml
> +        android:layout_height="39dp"
no hard code values

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout/fragment_gallery.xml
> +        android:textSize="20sp"
add this into [dimens](https://stackoverflow.com/questions/29128178/how-to-use-dimens-xml-in-android)

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout/fragment_gallery.xml
> +        app:layout_constraintHorizontal_bias="0.0"
delete bias

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout/fragment_gallery.xml
> +        app:layout_constraintVertical_bias="0.025" />
delete bias

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_height="36dp"
no hard code

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_marginEnd="8dp"
add this into [dimens](https://stackoverflow.com/questions/29128178/how-to-use-dimens-xml-in-android)

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout/fragment_slideshow.xml
> +        android:layout_marginEnd="8dp"
add this into [dimens](https://stackoverflow.com/questions/29128178/how-to-use-dimens-xml-in-android) and in the future places!

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout/fragment_slideshow.xml
> +        android:layout_height="589dp"
delete hardcode here and bias in the future places

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout/fragment_slideshow.xml
> +
empty line

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/layout/item.xml
> +    <!--   <TextView
commented code

2022-09-26 11:07 UTC, daddymercury commented on app/src/main/res/menu/main.xml
> + <!--
commented?

2022-09-26 18:31 UTC, chikebaba reviewed
Changes according to review (code and dimens)

2022-09-27 07:25 UTC, daddymercury requested changes

2022-09-27 07:25 UTC, daddymercury commented on app/src/main/java/com/example/android_task/ui/gallery/GalleryFragment.kt
> +        watchedText.addTextChangedListener(object : TextWatcher {
https://developer.android.com/reference/kotlin/androidx/core/widget/package-summary#(android.widget.TextView).doOnTextChanged(kotlin.Function4)

2022-09-27 07:25 UTC, daddymercury commented on app/src/main/java/com/example/android_task/ui/gallery/GalleryFragment.kt
> +        watchedText.addTextChangedListener(object : TextWatcher {
use this method here and delete Textwatcher with 3 methods

2022-09-27 07:25 UTC, daddymercury commented on app/src/main/java/com/example/android_task/ui/gallery/GalleryViewModel.kt
> +        value = "This is fragment with echo editText"
It looks like this string used in 2+ places add please this into constants

2022-09-27 07:25 UTC, daddymercury commented on app/src/main/res/layout/fragment_gallery.xml
> +        android:layout_width="match_parent"
use 0 dp instead

2022-09-27 07:25 UTC, daddymercury commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_width="match_parent"
please use 0dp

2022-09-27 07:25 UTC, daddymercury commented on app/src/main/res/layout/fragment_home.xml
>          app:layout_constraintVertical_bias="0.011" />
try to avoid using bias

2022-09-27 07:25 UTC, daddymercury commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_width="match_parent"
please use 0 dp instead

2022-09-27 07:25 UTC, daddymercury commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_width="match_parent"
please use 0 dp instead

2022-09-27 07:25 UTC, daddymercury commented on app/src/main/res/layout/fragment_slideshow.xml
> +        android:layout_width="match_parent"
please use 0 dp instead

2022-09-27 07:31 UTC, chikebaba commented on app/src/main/java/com/example/android_task/ui/gallery/GalleryViewModel.kt
> +        value = "This is fragment with echo editText"
It is used only in one place - in second fragment in one textview

2022-09-27 10:37 UTC, merged